-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS weather_station;
USE weather_station;

-- Make sure the table exists
CREATE TABLE IF NOT EXISTS weather_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  temperature FLOAT NOT NULL,
  humidity FLOAT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data for the past 24 hours
-- Earlier today
INSERT INTO weather_data (temperature, humidity, timestamp) VALUES
(18.5, 65, DATE_SUB(NOW(), INTERVAL 10 HOUR)),
(19.2, 64, DATE_SUB(NOW(), INTERVAL 9 HOUR)),
(20.1, 63, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
(21.5, 62, DATE_SUB(NOW(), INTERVAL 7 HOUR)),
(22.3, 60, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
(23.1, 58, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
(23.8, 55, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
(24.2, 53, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
(23.9, 54, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
(23.5, 55, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
(23.2, 56, NOW());

-- Yesterday
INSERT INTO weather_data (temperature, humidity, timestamp) VALUES
(17.2, 70, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(18.5, 68, DATE_SUB(NOW(), INTERVAL 23 HOUR)),
(19.8, 65, DATE_SUB(NOW(), INTERVAL 22 HOUR)),
(21.0, 62, DATE_SUB(NOW(), INTERVAL 21 HOUR)),
(22.5, 60, DATE_SUB(NOW(), INTERVAL 20 HOUR)),
(23.2, 58, DATE_SUB(NOW(), INTERVAL 19 HOUR)),
(22.8, 59, DATE_SUB(NOW(), INTERVAL 18 HOUR)),
(21.5, 62, DATE_SUB(NOW(), INTERVAL 17 HOUR)),
(20.2, 64, DATE_SUB(NOW(), INTERVAL 16 HOUR)),
(19.5, 67, DATE_SUB(NOW(), INTERVAL 15 HOUR)),
(18.8, 69, DATE_SUB(NOW(), INTERVAL 14 HOUR)),
(18.2, 70, DATE_SUB(NOW(), INTERVAL 13 HOUR)),
(17.9, 72, DATE_SUB(NOW(), INTERVAL 12 HOUR)),
(17.5, 73, DATE_SUB(NOW(), INTERVAL 11 HOUR)); 